name: Test and Deploy 

on:
  push:              
    branches:
      - main

jobs:              
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello everyone from the pipeline!'
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
# ------------------ ADD BEFORE INSTALLING THE DEPS ----------------------
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1 # action from the marketplace
        with: # telling it to use these credentials 
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55w0rd # very secure

    - name: Install dependencies
      run: npm install

    - name: Test utils and app # improve the descriptive name
      run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55w0rd npm test