name: Test and Deploy # provide a name

on:
  push:               # tell it when to run
    branches:
      - main

jobs:                # determine what we want to happen when the workflow runs
  greeting:
    runs-on: ubuntu-latest # specify WHAT OS we'd like our code to run on (linux is cheapest)
    steps:            # lay out the steps for the job - in this case, say Hello
      - name: Say hello
        run: echo 'Hello everyone from the pipeline!'