name: Test and Deploy

on:
  push: # telling it when to run 
    branches: 
      - main
jobs: 
  greeting:  #name provided for each job - should be unique
    runs-on: ubuntu-latest # specifying the OS for our VM 
    steps: 
      - name: Say Hi
        run: echo "Hello from the pipeline!"

  # clone --> install deps --> npm test
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout and clone repo # descriptive 
        uses: actions/checkout@v2 

      - name: setup Postgres
        uses: harmon758/postgresql-action@v1
        with: 
          postgresql db: test_db
          postgresql user: clive_onion
          postgresql password: password

      - name: Install Deps 
        run: npm install

      - name: Its Testing Time!
        run: PGDATABASE=test_db PGUSER=clive_onion PGPASSWORD=password npm test
      
